spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:secrets/application-local.yml

---

spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:secrets/application-dev.yml

---

spring:
  config:
    activate:
      on-profile: prod
    import:
      - classpath:secrets/application-prod.yml
