spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:secrets/application-local.yml

---

spring:
  config:
    activate:
      on-profile: develop
    import:
      - classpath:secrets/application-dev.yml

---

spring:
  config:
    activate:
      on-profile: production
    import:
      - classpath:secrets/application-prod.yml
